#!/bin/bash

set -euo pipefail

RED='\033[38;2;0;0;0;48;2;255;0;0;1m'
NORMAL='\033[0m'
MASTER_BRANCH_RESTRICTED="eirini-release garden-runc-release"

main() {
  local repo_name
  repo_name=$(repo-name)

  while read -r _ _ remote_ref _; do
    if [[ " ${MASTER_BRANCH_RESTRICTED[@]} " =~ " ${repo_name} " ]]; then
      prevent_push_to_master
    fi
  done
}

prevent_push_to_master() {
  if [[ "$remote_ref" =~ .*/master$ ]]; then
    echo -e "${RED}   Do not push to master. Never.   ${NORMAL}"
    exit 1
  fi
}

repo-name() {
  git_dir="$(git rev-parse --show-toplevel)"
  basename $git_dir
}

main
