#!/bin/bash

set -euo pipefail

RED='\033[38;2;0;0;0;48;2;255;0;0;1m'
NORMAL='\033[0m'
EIRINI_REPOS="eirini eirini-ci eirini-private-config eirini-release"

main() {
  local repo_name
  repo_name=$(repo-name)

  while read -r _ _ remote_ref _; do
    local dev_branch
    dev_branch="master"

    if [[ "$repo_name" == "eirini-release" ]]; then
      dev_branch="develop"
    fi

    check_push_to_dev_branch $dev_branch
  done
}

check_push_to_dev_branch() {
  local dev_branch
  dev_branch=$1

  if [[ "$remote_ref" =~ .*/$dev_branch$ ]]; then
    check-eirini-project
    check-ci
  fi
}

repo-name() {
  git_dir="$(git rev-parse --show-toplevel)"
  basename $git_dir
}

check-eirini-project() {
  local repo_name
  repo_name=$(repo-name)

  if [[ ! " ${EIRINI_REPOS[@]} " =~ " ${repo_name} " ]]; then
    echo 'Skipping CI checks'
    exit 0
  fi
}

check-ci() {
  if check-pipeline "ci" || check-pipeline "acceptance"; then
    echo -e "${RED}   Pipeline is red.    ${NORMAL}"
    prompt-push
  fi
  echo "CI is green"
}

ensure-tty() {
  if ! exec 1001</dev/tty; then
    echo "not in a terminal - giving up. Please retry from the command line"
    exit 3
  fi
  1001<&-
}

prompt-push() {
  ensure-tty
  read -r -p "Do you want to push? [y/N]" yn </dev/tty
  case $yn in
    [Yy]) exit 0 ;;
    *)
      echo 'Bailing out'
      exit 1
      ;;
  esac
}

fly-login() {
  if ! flightattendant -target eirini; then
    echo "not logged in to concourse - attempting to log in"
    ensure-tty
    fly -t eirini login --team-name main --concourse-url https://jetson.eirini.cf-app.com/ </dev/tty
  fi
}

check-pipeline() {
  local pipeline_name failed_jobs
  pipeline_name="$1"
  echo "Checking https://jetson.eirini.cf-app.com/teams/main/pipelines/$pipeline_name ..."
  fly-login
  output=$(fly -t eirini jobs -p "$1")
  if [ "$?" -ne "0" ]; then
    echo "fly failed - giving up!"
    exit 1
  fi
  echo "$output" | grep -Eq "failed|error"
}

main
