#!/bin/bash

set -euo pipefail

config_file="$HOME/.gitconfig"
pass_token=eirini/github/eirinici/gh-access-token

export author_initials="$(awk '/git-author-initials/ { print $3 }' "$config_file")"
author_username="$(awk -v id="$author_initials" '{ if ($1 ~ id && usernames==1) print $2 }; /^usernames:/ { usernames=1 }' $HOME/.git-authors)"

if ! gh auth status &>/dev/null; then
  pass "$pass_token" | gh auth login --with-token
fi

for issue_id in $(gh issue list \
  -a "$author_username" \
  -R cloudfoundry-incubator/eirini-release \
  -S sort:updated-asc |
  awk ' { print "[cloudfoundry-incubator/eirini-release#" $1 "]" }'); do
  sed -i "1s;^;$issue_id;" "$1"
done
