#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

source $SCRIPT_DIR/common

if ! git symbolic-ref -q HEAD; then
  echo -e "${bold}Uh oh!  It looks like you're in a ${red}detached head${default} state!${normal}"
  echo
  echo "Please consider checking out a proper branch before committing"
  prompt_user
fi
