#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)
red="\033[31m"
blue="\033[34m"
default="\033[0;1m"

prompt_user() {
  exec </dev/tty
  read -p "Do you want to continue? [y/N] " -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    exit 0
  fi
  exit 1
}
